name: Build Windows EXE
on: [push]  # 代码推送时自动运行

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 拉取代码

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        pip install pyinstaller
        if exist requirements.txt pip install -r requirements.txt

    - name: Build EXE
      run: pyinstaller --onefile hello.py  # 替换为你的脚本名

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/  # 生成的 EXE 在 dist 文件夹
